AllCops:
  NewCops: enable

  Exclude:
    - 'Gemfile'
    - 'config.ru'
    - 'config/**/*'
    - 'bin/**'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'app/services/service_module.rb'