AllCops:
  NewCops: enable

  Exclude:
    - "Gemfile"
    - "config.ru"
    - "config/**/*"
    - "bin/**"
    - "db/schema.rb"
    - "lib/tasks/auto_annotate_models.rake"
    - "app/services/service_module.rb"

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Max: 30
